
name: Sample CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [foo, bar, baz]
        include:
          - subpackage: bizz
            package: baz

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "${{matrix.package}} - ${{matrix.subpackage}} - Hello, world!"

  report:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Report success
        uses: myrotvorets/set-commit-status-action@master
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          sha: ${{ github.sha }}
          status: "success"
          context: "foo-bar-baz-checks" 
