
name: Sample CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        package: [foo, bar, baz]

    steps:
      - uses: actions/checkout@v3

      - name: Run a one-line script
        run: echo "${{matrix.package}} - Hello, world!"
